### ISSUE TITLE
Feature request: cell-wise execution for Julia/Juno

### ISSUE THREAD

**Issue by twadleigh** [mpastell/language-weave#11]
It would be great to have an analog of `julia-client:run-cell-and-move` for (non-script) weave documents. Of course, weave already has a natural notion of cell, but even better would be if this command recognized "subcells" as well: I'm thinking of code chunks that, _e.g._, can be further divided by `##` for interactive evaluation.

**Comment by pfitzseb** [comment]
This should work with the latest versions of language-weave and Juno.

**Comment by mpastell** [comment]
This works very nicely in the latest release thanks to  @pfitzseb!
