### ISSUE TITLE
language-weave stealing ~, !, and @

### ISSUE THREAD

**Issue by ssfrr** [mpastell/language-weave#15]
After updating language-weave I noticed that I'm suddenly unable to type `~`, `!`, and `@` from within a julia block in a weave file. It looks like those keybindings are now triggering the commands `markdown:strike-through`, `markdown:image`, and `markdown:link`, but not actually typing the characters.

**Comment by kescobo** [comment]
Also Tab...

**Comment by pfitzseb** [comment]
I think those keybindings should just be removed (and maybe replaced by snippets if anyone feels they would be useful),

**Comment by pfitzseb** [comment]
Until this is resolved you can either disable this packages keybindings or install https://github.com/burodepeper/language-markdown, which will provide the relevant commands.

**Comment by mpastell** [comment]
This works for me now using language-weave 0.5.0, many thanks to @pfitzseb for the fix!

**Comment by marius311** [comment]
I have `language-markdown 0.29.0`, `language-weave 0.6.1`, and `atom 1.35.1` and I can't type `@`, `*`, `!`, or `<Tab>` in a `Weave.jl markdown` file. Am I doing something wrong? This the keybinding resolver when trying to type, e.g. `@`:

![image](https://user-images.githubusercontent.com/1510968/54942639-c2dca800-4eec-11e9-9116-b2b5acbc6588.png)

**Comment by marius311** [comment]
Also, if I disable `language-weave` keybindings then I can type these, but then `Ctrl+Enter` no longer evaluates Julia code in-line, so that's not a full solution either.

**Comment by pfitzseb** [comment]
Ok, should work fine again with the latest release...

**Comment by marius311** [comment]
I confirm it does for me, thanks!
