### ISSUE TITLE
Markdown parts of .jmd not highlighting

### ISSUE THREAD

**Issue by kescobo** [mpastell/language-weave#5]
Just came back to wanting to use .jmd notebooks for code, but the markdown syntax highlighting isn't working (julia highlighting is). 

Note the bold text:

![screenshot 2017-07-18 17 15 48](https://user-images.githubusercontent.com/3502975/28340250-0b55cd22-6bdd-11e7-96a5-9abe4581c305.png)

And some other formatting:

![screenshot 2017-07-18 17 16 05](https://user-images.githubusercontent.com/3502975/28340272-184a8c16-6bdd-11e7-9543-fbf6bed5ac94.png)

`Weave.jl markdown` is auto-detected as the file type. I'm on Atom v1.18.0, language-weave v0.4.0

If I switch file type to plain markdown, the highlighting works but I lose the lovely ability to execute code in codeblocks with juno.

**Comment by mpastell** [comment]
The highlighting works for me. Do you have some other package disabling `language-gfm`

**Comment by kescobo** [comment]
@mpastell Oh, that's interesting - `language-gfm` was indeed disabled, though I'm not sure what did it. In any case, re-enabling that did solve the problem. Thanks!
